[program:bbapi]
command=/root/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8001
directory=/app/backend
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/bbapi.out.log
stopsignal=TERM
stopasgroup=true
killasgroup=true
