/* Otomatik uretildi: _analysis/logo_map.json (onceki oturumun 112 kanal listesi). Kaynaklar backend'de (/api/stream/{id}/stream.m3u8). */
export type CatalogChannel = { id: string; name: string; short: string; cat: string; logo: string; accent: string; premium?: boolean };
export const CATEGORIES = ['TUMU','SPOR','ULUSAL','HABER','MUZIK','COCUK','SINEMA','BELGESEL'] as const;
export const CATEGORY_LABEL: Record<string,string> = { TUMU:'TÜMÜ', SPOR:'SPOR', ULUSAL:'ULUSAL', HABER:'HABER', MUZIK:'MÜZİK', COCUK:'ÇOCUK', SINEMA:'SİNEMA', BELGESEL:'BELGESEL', DIGER:'DİĞER' };
export const CATALOG: CatalogChannel[] = [
  { id: "bein1", name: "BEIN SPORTS 1", short: "BEIN SPORTS ", cat: "SPOR", logo: "https://static.wikia.nocookie.net/logopedia/images/2/27/BeinSports1.svg/revision/latest?cb=20230910184457", accent: "#ff4fd8", premium: true },
  { id: "bein2", name: "BEIN SPORTS 2", short: "BEIN SPORTS ", cat: "SPOR", logo: "https://static.wikia.nocookie.net/logopedia/images/4/40/BeinSports2.svg/revision/latest?cb=20230910185720", accent: "#ff4fd8", premium: true },
  { id: "bein3", name: "BEIN SPORTS 3", short: "BEIN SPORTS ", cat: "SPOR", logo: "https://static.wikia.nocookie.net/logopedia/images/5/53/BeIN_Sports_3_2017_Rectangle.png/revision/latest/scale-to-width-down/1000?cb=20251213114000", accent: "#ff4fd8", premium: true },
  { id: "bein4", name: "BEIN SPORTS 4", short: "BEIN SPORTS ", cat: "SPOR", logo: "https://static.wikia.nocookie.net/logopedia/images/9/96/Logo_bein_sports_4.png/revision/latest/scale-to-width-down/1000?cb=20251213115820", accent: "#ff4fd8", premium: true },
  { id: "bein5", name: "BEIN SPORTS 5", short: "BEIN SPORTS ", cat: "SPOR", logo: "https://static.wikia.nocookie.net/logopedia/images/1/14/BeIN%2Bsports%2B5.png/revision/latest/scale-to-width-down/1000?cb=20251214104942", accent: "#ff4fd8", premium: true },
  { id: "beinmax1", name: "BEIN SPORTS MAX 1", short: "BEIN SPORTS ", cat: "SPOR", logo: "https://i.imgur.com/FjWQjdy.png", accent: "#ff4fd8", premium: true },
  { id: "beinmax2", name: "BEIN SPORTS MAX 2", short: "BEIN SPORTS ", cat: "SPOR", logo: "https://i.imgur.com/5dBc5rn.png", accent: "#ff4fd8", premium: true },
  { id: "beinxtra", name: "BEIN SPORTS XTRA", short: "BEIN SPORTS ", cat: "SPOR", logo: "https://i.ibb.co/HT49GPmB/XTRA-2.png", accent: "#ff4fd8" },
  { id: "ssport", name: "S SPORT", short: "S SPORT", cat: "SPOR", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/S_Sport_logo1.png", accent: "#ff4fd8", premium: true },
  { id: "ssport2", name: "S SPORT 2", short: "S SPORT 2", cat: "SPOR", logo: "https://i.imgur.com/2jIItAy.png", accent: "#ff4fd8", premium: true },
  { id: "smart1", name: "SPOR SMART", short: "SPOR SMART", cat: "SPOR", logo: "https://i.imgur.com/blu6v6P.png", accent: "#ff4fd8", premium: true },
  { id: "smart2", name: "SPOR SMART 2", short: "SPOR SMART 2", cat: "SPOR", logo: "https://i.imgur.com/qyUKCUa.png", accent: "#ff4fd8", premium: true },
  { id: "tivibuspor", name: "TIVIBU SPOR", short: "TIVIBU SPOR", cat: "SPOR", logo: "https://i.imgur.com/qvrKQY3.png", accent: "#ff4fd8", premium: true },
  { id: "tivibuspor2", name: "TIVIBU SPOR 2", short: "TIVIBU SPOR ", cat: "SPOR", logo: "https://i.imgur.com/fZMSjNE.png", accent: "#ff4fd8", premium: true },
  { id: "tivibuspor3", name: "TIVIBU SPOR 3", short: "TIVIBU SPOR ", cat: "SPOR", logo: "https://i.imgur.com/xLrgt2O.png", accent: "#ff4fd8", premium: true },
  { id: "tivibuspor4", name: "TIVIBU SPOR 4", short: "TIVIBU SPOR ", cat: "SPOR", logo: "https://i.imgur.com/LgGxe7z.png", accent: "#ff4fd8", premium: true },
  { id: "tabiispor", name: "TABII SPOR 6", short: "TABII SPOR 6", cat: "SPOR", logo: "https://cms-tabii-public-image.tabii.com/int/w300/43020.jpeg", accent: "#ff4fd8" },
  { id: "trtspor", name: "TRT SPOR", short: "TRT SPOR", cat: "SPOR", logo: "https://i.imgur.com/6tv0zxh.png", accent: "#ff4fd8" },
  { id: "trtsporyildiz", name: "TRT SPOR", short: "TRT SPOR", cat: "SPOR", logo: "https://i.imgur.com/6tv0zxh.png", accent: "#ff4fd8" },
  { id: "aspor", name: "A SPOR", short: "A SPOR", cat: "SPOR", logo: "https://i.imgur.com/ZhkZzLf.png", accent: "#ff4fd8" },
  { id: "htspor", name: "HTSPOR TV", short: "HTSPOR TV", cat: "SPOR", logo: "https://www.htspor.com/images/manifest/social-share-logo.png", accent: "#ff4fd8" },
  { id: "tjktv", name: "TJK TV", short: "TJK TV", cat: "SPOR", logo: "https://i.imgur.com/3zHdkYG.png", accent: "#ff4fd8" },
  { id: "fbtv", name: "FB TV", short: "FB TV", cat: "SPOR", logo: "https://i.imgur.com/qBVqtYd.png", accent: "#ff4fd8" },
  { id: "nbatv", name: "NBA TV", short: "NBA TV", cat: "SPOR", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/NBA_TV.svg/960px-NBA_TV.svg.png", accent: "#ff4fd8" },
  { id: "fifaplus", name: "FIFA+", short: "FIFA+", cat: "SPOR", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/FIFA%2B_(2025).svg/960px-FIFA%2B_(2025).svg.png", accent: "#ff4fd8" },
  { id: "eurosport1", name: "EUROSPORT 1", short: "EUROSPORT 1", cat: "SPOR", logo: "https://i.imgur.com/olQJgm7.png", accent: "#ff4fd8" },
  { id: "redbulltv", name: "RED BULL TV", short: "RED BULL TV", cat: "SPOR", logo: "https://images.pluto.tv/channels/5e7cb84a172a0f0007da69e4/colorLogoPNG.png", accent: "#ff4fd8" },
  { id: "tracesport", name: "TRACE SPORT STARS", short: "TRACE SPORT ", cat: "SPOR", logo: "https://i.imgur.com/FabFP5A.png", accent: "#ff4fd8" },
  { id: "ktvsport", name: "KTV SPORT PLUS", short: "KTV SPORT PL", cat: "SPOR", logo: "https://i.imgur.com/l4oX0gf.png", accent: "#ff4fd8" },
  { id: "fightbox", name: "FIGHTBOX", short: "FIGHTBOX", cat: "SPOR", logo: "https://i.imgur.com/mRsnztA.png", accent: "#ff4fd8" },
  { id: "glory", name: "GLORY KICKBOXING", short: "GLORY KICKBO", cat: "SPOR", logo: "https://i.imgur.com/tS7Ub7i.png", accent: "#ff4fd8" },
  { id: "realmadridtv", name: "REAL MADRID TV", short: "REAL MADRID ", cat: "SPOR", logo: "https://i.imgur.com/5pMo7dL.png", accent: "#ff4fd8" },
  { id: "nhl", name: "NHL NETWORK", short: "NHL NETWORK", cat: "SPOR", logo: "https://i.imgur.com/UNZ8bef.png", accent: "#ff4fd8" },
  { id: "trt1", name: "TRT 1", short: "TRT 1", cat: "ULUSAL", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/TRT_1_logo_%282021-%29.svg/960px-TRT_1_logo_%282021-%29.svg.png", accent: "#38e8ff" },
  { id: "trt2", name: "TRT 2", short: "TRT 2", cat: "ULUSAL", logo: "https://i.imgur.com/iOCQdyD.png", accent: "#38e8ff" },
  { id: "showtv", name: "SHOW TV", short: "SHOW TV", cat: "ULUSAL", logo: "https://i.imgur.com/1l7SCCu.png", accent: "#38e8ff" },
  { id: "atv", name: "ATV", short: "ATV", cat: "ULUSAL", logo: "https://i.imgur.com/HyVUwFC.png", accent: "#38e8ff" },
  { id: "kanald", name: "KANAL D", short: "KANAL D", cat: "ULUSAL", logo: "https://i.imgur.com/9o1atM6.png", accent: "#38e8ff" },
  { id: "startv", name: "STAR TV", short: "STAR TV", cat: "ULUSAL", logo: "https://i.imgur.com/9O3DHRB.png", accent: "#38e8ff" },
  { id: "nowtv", name: "NOW BAOGU MOVIES", short: "NOW BAOGU MO", cat: "ULUSAL", logo: "https://i.imgur.com/3BnztrM.png", accent: "#38e8ff" },
  { id: "tv8", name: "TV8", short: "TV8", cat: "ULUSAL", logo: "https://upload.wikimedia.org/wikipedia/tr/thumb/6/68/Tv8_Yeni_Logo.png/960px-Tv8_Yeni_Logo.png", accent: "#38e8ff" },
  { id: "tv85", name: "TV 8.5", short: "TV 8.5", cat: "ULUSAL", logo: "https://i.imgur.com/QuelSsc.png", accent: "#38e8ff" },
  { id: "kanal7", name: "KANAL 7", short: "KANAL 7", cat: "ULUSAL", logo: "https://i.imgur.com/0gq9xOm.png", accent: "#38e8ff" },
  { id: "teve2", name: "TV2", short: "TV2", cat: "ULUSAL", logo: "https://i.imgur.com/rsoSLih.png", accent: "#38e8ff" },
  { id: "beyaztv", name: "BEYAZ TV", short: "BEYAZ TV", cat: "ULUSAL", logo: "https://i.imgur.com/uykIdML.png", accent: "#38e8ff" },
  { id: "tv100", name: "TV 100", short: "TV 100", cat: "ULUSAL", logo: "https://upload.wikimedia.org/wikipedia/tr/thumb/0/0f/TV100_logo.png/960px-TV100_logo.png", accent: "#38e8ff" },
  { id: "tabii", name: "TABII SPOR 6", short: "TABII SPOR 6", cat: "ULUSAL", logo: "https://cms-tabii-public-image.tabii.com/int/w300/43020.jpeg", accent: "#38e8ff" },
  { id: "trtturk", name: "TRT", short: "TRT", cat: "ULUSAL", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/TRT_T%C3%BCrk_logo.svg/960px-TRT_T%C3%BCrk_logo.svg.png", accent: "#38e8ff" },
  { id: "a2", name: "A2", short: "A2", cat: "ULUSAL", logo: "https://i.imgur.com/NqHla2V.png", accent: "#38e8ff" },
  { id: "tv360", name: "360", short: "360", cat: "ULUSAL", logo: "https://i.imgur.com/agn47sQ.png", accent: "#38e8ff" },
  { id: "trthaber", name: "TRT HABER", short: "TRT HABER", cat: "HABER", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/TRT_Haber_Eyl%C3%BCl_2020_Logo.svg/960px-TRT_Haber_Eyl%C3%BCl_2020_Logo.svg.png", accent: "#ff3b5c" },
  { id: "ntv", name: "NTV", short: "NTV", cat: "HABER", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/NTV_%28Turkey%29_logo.svg/960px-NTV_%28Turkey%29_logo.svg.png", accent: "#ff3b5c" },
  { id: "cnnturk", name: "CNN", short: "CNN", cat: "HABER", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/CNN_T%C3%BCrk_logo.svg/960px-CNN_T%C3%BCrk_logo.svg.png", accent: "#ff3b5c" },
  { id: "haberturk", name: "HABERTURK TV", short: "HABERTURK TV", cat: "HABER", logo: "https://i.imgur.com/6Tw3rUp.png", accent: "#ff3b5c" },
  { id: "ahaber", name: "A HABER", short: "A HABER", cat: "HABER", logo: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Ahaber_Logo.png", accent: "#ff3b5c" },
  { id: "haberglobal", name: "HABER GLOBAL", short: "HABER GLOBAL", cat: "HABER", logo: "https://i.imgur.com/fu6XeGS.png", accent: "#ff3b5c" },
  { id: "halktv", name: "HALK TV", short: "HALK TV", cat: "HABER", logo: "https://i.imgur.com/xM0HA30.png", accent: "#ff3b5c" },
  { id: "tgrthaber", name: "TGRT HABER", short: "TGRT HABER", cat: "HABER", logo: "https://i.imgur.com/PrxwKDw.png", accent: "#ff3b5c" },
  { id: "bloomberght", name: "BLOOMBERG HT", short: "BLOOMBERG HT", cat: "HABER", logo: "https://i.imgur.com/bmkXfIE.png", accent: "#ff3b5c" },
  { id: "sozcutv", name: "SOZCU TV", short: "SOZCU TV", cat: "HABER", logo: "https://i.imgur.com/BxpdvsG.png", accent: "#ff3b5c" },
  { id: "tele1", name: "TELE 1", short: "TELE 1", cat: "HABER", logo: "https://upload.wikimedia.org/wikipedia/tr/4/43/Tele1_logosu.png", accent: "#ff3b5c" },
  { id: "ulketv", name: "ULKE TV", short: "ULKE TV", cat: "HABER", logo: "https://i.imgur.com/wdWR7Qk.png", accent: "#ff3b5c" },
  { id: "kanal24", name: "KANAL 2", short: "KANAL 2", cat: "HABER", logo: "https://i.imgur.com/Ulfl56H.png", accent: "#ff3b5c" },
  { id: "trtworld", name: "TRT WORLD", short: "TRT WORLD", cat: "HABER", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/TRT_World.svg/960px-TRT_World.svg.png", accent: "#ff3b5c" },
  { id: "flashhaber", name: "FLASH", short: "FLASH", cat: "HABER", logo: "https://i.imgur.com/OXdYBAh.png", accent: "#ff3b5c" },
  { id: "dha", name: "DHA", short: "DHA", cat: "HABER", logo: "https://i.imgur.com/VZhag2x.png", accent: "#ff3b5c" },
  { id: "tbmmtv", name: "TBMM TV", short: "TBMM TV", cat: "HABER", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/TBMM_TV_logo.svg/960px-TBMM_TV_logo.svg.png", accent: "#ff3b5c" },
  { id: "kralpop", name: "KRAL POP TV", short: "KRAL POP TV", cat: "MUZIK", logo: "https://i.imgur.com/ch365lh.png", accent: "#ffc857" },
  { id: "dreamturk", name: "DREAM", short: "DREAM", cat: "MUZIK", logo: "https://i.imgur.com/vJ8VaZi.png", accent: "#ffc857" },
  { id: "powerturk", name: "POWERTURK TV", short: "POWERTURK TV", cat: "MUZIK", logo: "https://i.imgur.com/9OPoXQG.png", accent: "#ffc857" },
  { id: "power", name: "POWER TV", short: "POWER TV", cat: "MUZIK", logo: "https://i.imgur.com/XSL1gd7.png", accent: "#ffc857" },
  { id: "trtmuzik", name: "TRT MUZIK", short: "TRT MUZIK", cat: "MUZIK", logo: "https://i.imgur.com/JgUzRH8.png", accent: "#ffc857" },
  { id: "4turkpop", name: "4", short: "4", cat: "MUZIK", logo: "https://i.imgur.com/nPqRAmr.png", accent: "#ffc857" },
  { id: "trtcocuk", name: "TRT COCUK", short: "TRT COCUK", cat: "COCUK", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/TRT_%C3%87ocuk_logo_%282021%29.svg/960px-TRT_%C3%87ocuk_logo_%282021%29.svg.png", accent: "#39ff88" },
  { id: "minikacocuk", name: "MINIKA COCUK", short: "MINIKA COCUK", cat: "COCUK", logo: "https://i.imgur.com/VCywMTv.png", accent: "#39ff88" },
  { id: "minikago", name: "MINIKA GO", short: "MINIKA GO", cat: "COCUK", logo: "https://i.imgur.com/qIoipDq.png", accent: "#39ff88" },
  { id: "cartoonnetwork", name: "CARTOON NETWORK", short: "CARTOON NETW", cat: "COCUK", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/960px-Cartoon_Network_2010_logo.svg.png", accent: "#39ff88" },
  { id: "cartoonito", name: "CARTOONITO", short: "CARTOONITO", cat: "COCUK", logo: "https://i.imgur.com/6vYWCD0.png", accent: "#39ff88" },
  { id: "nicktoons", name: "NICKTOONS", short: "NICKTOONS", cat: "COCUK", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Nicktoons_UK_Logo_2014.png", accent: "#39ff88" },
  { id: "trteba", name: "TRT EBA", short: "TRT EBA", cat: "COCUK", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/TRT_EBA_TV_logo.svg/960px-TRT_EBA_TV_logo.svg.png", accent: "#39ff88" },
  { id: "zarok", name: "ZAROK TV", short: "ZAROK TV", cat: "COCUK", logo: "https://i.imgur.com/o0eevnb.png", accent: "#39ff88" },
  { id: "beinboxoffice1", name: "BEIN BOX OFFICE 1", short: "BEIN BOX OFF", cat: "SINEMA", logo: "https://i.imgur.com/MGrJFVN.png", accent: "#a64dff", premium: true },
  { id: "beinboxoffice2", name: "BEIN BOX OFFICE 2", short: "BEIN BOX OFF", cat: "SINEMA", logo: "https://i.imgur.com/Kg7oOcO.png", accent: "#a64dff", premium: true },
  { id: "beinboxoffice3", name: "BEIN BOX OFFICE 3", short: "BEIN BOX OFF", cat: "SINEMA", logo: "https://i.imgur.com/5NZur1S.png", accent: "#a64dff", premium: true },
  { id: "beinmoviesaction", name: "BEIN MOVIES ACTION", short: "BEIN MOVIES ", cat: "SINEMA", logo: "https://i.imgur.com/AUWa7bk.png", accent: "#a64dff", premium: true },
  { id: "beinmoviesfamily", name: "BEIN MOVIES FAMILY", short: "BEIN MOVIES ", cat: "SINEMA", logo: "https://i.imgur.com/PVUclcU.png", accent: "#a64dff", premium: true },
  { id: "beinmoviespremier", name: "BEIN MOVIES PREMIERE", short: "BEIN MOVIES ", cat: "SINEMA", logo: "https://i.imgur.com/SVwK50e.png", accent: "#a64dff", premium: true },
  { id: "beinmoviesstars", name: "BEIN MOVIES STARS", short: "BEIN MOVIES ", cat: "SINEMA", logo: "https://i.imgur.com/eryPkrT.png", accent: "#a64dff", premium: true },
  { id: "beinmoviesturk", name: "BEIN MOVIES", short: "BEIN MOVIES", cat: "SINEMA", logo: "https://i.imgur.com/nw8Sa2z.png", accent: "#a64dff", premium: true },
  { id: "sinematv", name: "SINEMA TV", short: "SINEMA TV", cat: "SINEMA", logo: "https://i.imgur.com/qstBXDP.png", accent: "#a64dff" },
  { id: "sinematvaksiyon", name: "SINEMA TV", short: "SINEMA TV", cat: "SINEMA", logo: "https://i.imgur.com/qstBXDP.png", accent: "#a64dff" },
  { id: "sinematvaksiyon2", name: "SINEMA TV", short: "SINEMA TV", cat: "SINEMA", logo: "https://i.imgur.com/qstBXDP.png", accent: "#a64dff" },
  { id: "sinematvaile", name: "SINEMA TV", short: "SINEMA TV", cat: "SINEMA", logo: "https://i.imgur.com/qstBXDP.png", accent: "#a64dff" },
  { id: "sinematvkomedi", name: "SINEMA TV", short: "SINEMA TV", cat: "SINEMA", logo: "https://i.imgur.com/qstBXDP.png", accent: "#a64dff" },
  { id: "sinematvyerli", name: "SINEMA TV", short: "SINEMA TV", cat: "SINEMA", logo: "https://i.imgur.com/qstBXDP.png", accent: "#a64dff" },
  { id: "sinematv1001", name: "SINEMA TV", short: "SINEMA TV", cat: "SINEMA", logo: "https://i.imgur.com/qstBXDP.png", accent: "#a64dff" },
  { id: "sinematv1002", name: "SINEMA TV", short: "SINEMA TV", cat: "SINEMA", logo: "https://i.imgur.com/qstBXDP.png", accent: "#a64dff" },
  { id: "moviesmart", name: "MOVIES!", short: "MOVIES!", cat: "SINEMA", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Movies%21_logo.svg/960px-Movies%21_logo.svg.png", accent: "#a64dff", premium: true },
  { id: "moviesmartturk", name: "MOVIESMART", short: "MOVIESMART", cat: "SINEMA", logo: "https://i.imgur.com/DWN9ulT.png", accent: "#a64dff", premium: true },
  { id: "fx", name: "FX", short: "FX", cat: "SINEMA", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/FX_International_logo.svg/960px-FX_International_logo.svg.png", accent: "#a64dff" },
  { id: "trtbelgesel", name: "TRT BELGESEL", short: "TRT BELGESEL", cat: "BELGESEL", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/TRT_Belgesel_logo_%282019-%29.svg/960px-TRT_Belgesel_logo_%282019-%29.svg.png", accent: "#00c2ff" },
  { id: "natgeo", name: "NATIONAL GEOGRAPHIC", short: "NATIONAL GEO", cat: "BELGESEL", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Natgeologo.svg/960px-Natgeologo.svg.png", accent: "#00c2ff" },
  { id: "natgeowild", name: "NATIONAL GEOGRAPHIC WILD", short: "NATIONAL GEO", cat: "BELGESEL", logo: "https://i.imgur.com/HoeaQJC.png", accent: "#00c2ff" },
  { id: "bbcearth", name: "BBC EARTH", short: "BBC EARTH", cat: "BELGESEL", logo: "https://bbcearth.ca/wp-content/uploads/2024/02/BBCEarth_Logo-1.png", accent: "#00c2ff" },
  { id: "dmax", name: "DMAX", short: "DMAX", cat: "BELGESEL", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/DMAX_BLACK.svg/960px-DMAX_BLACK.svg.png", accent: "#00c2ff" },
  { id: "tlc", name: "TLC", short: "TLC", cat: "BELGESEL", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/TLC_Logo.svg/960px-TLC_Logo.svg.png", accent: "#00c2ff" },
  { id: "history", name: "HISTORY", short: "HISTORY", cat: "BELGESEL", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/History_Logo.svg/500px-History_Logo.svg.png", accent: "#00c2ff" },
  { id: "tarihtv", name: "TARIH TV", short: "TARIH TV", cat: "BELGESEL", logo: "https://i.imgur.com/HbIGZUt.png", accent: "#00c2ff" },
  { id: "lovenature", name: "LOVE NATURE", short: "LOVE NATURE", cat: "BELGESEL", logo: "https://tv.lovenature.com/wp-content/uploads/2024/10/LoveNature2024_Logo_full_colour-copy.png", accent: "#00c2ff" },
  { id: "docubox", name: "DOCUBOX", short: "DOCUBOX", cat: "BELGESEL", logo: "https://i.imgur.com/pX4U9OG.png", accent: "#00c2ff" },
  { id: "tgrtbelgesel", name: "TGRT BELGESEL", short: "TGRT BELGESE", cat: "BELGESEL", logo: "https://i.imgur.com/VwWTnf0.png", accent: "#00c2ff" },
  { id: "travelxp", name: "TRAVELXP", short: "TRAVELXP", cat: "BELGESEL", logo: "https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/transparentImages/Travelxp%20HD.png", accent: "#00c2ff" },
];
